import test from 'node:test';
import assert from 'node:assert/strict';
import { request as httpRequest } from 'node:http';
import { gunzipSync, brotliDecompressSync } from 'node:zlib';
import { mkdtemp, rm, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { loadPosts, SITE_ORIGIN, searchIndexScript } from '../blog.js';
import { createAppServer } from '../server.js';
const source = (title, date = '2026-09-14', extra = '', body = '## Heading\n\n**Strong** and [safe](https://example.com).') => `---\ntitle: ${title}\ndescription: A test field note\ndate: ${date}\n${extra}---\n${body}`;
async function directory(t) {
  const dir = await mkdtemp(join(tmpdir(), 'nfs-posts-'));
  t.after(() => rm(dir, { recursive:true, force:true }));
  return dir;
}
test('posts load newest first, support Markdown, and reflect folder edits without a restart', async t => {
  const dir = await directory(t);
  await writeFile(join(dir, 'first.md'), source('First', '2026-09-01'));
  await writeFile(join(dir, 'second.md'), source('Second'));
  let posts = await loadPosts(dir);
  assert.deepEqual(posts.map(p => p.slug), ['second', 'first']);
  assert.match(posts[0].html, /<h2>Heading<\/h2>/);
  assert.match(posts[0].html, /<strong>Strong<\/strong>/);
  await writeFile(join(dir, 'second.md'), source('Edited'));
  posts = await loadPosts(dir);
  assert.equal(posts[0].title, 'Edited');
  await rm(join(dir, 'second.md'));
  assert.equal((await loadPosts(dir)).length, 1);
});
test('drafts, malformed metadata, invalid dates and non-post files are excluded', async t => {
  const dir = await directory(t);
  await writeFile(join(dir, 'draft.md'), source('Draft', '2026-09-14', 'draft: true\n'));
  await writeFile(join(dir, 'invalid.md'), 'no front matter');
  await writeFile(join(dir, 'bad-date.md'), source('Bad date', '2026-02-30'));
  await writeFile(join(dir, 'README.md'), source('Instructions'));
  await writeFile(join(dir, 'good.md'), source('Good'));
  assert.deepEqual((await loadPosts(dir)).map(p => p.slug), ['good']);
  assert.deepEqual(await loadPosts(join(dir, 'missing')), []);
});
test('Markdown escapes raw HTML and refuses executable links', async t => {
  const dir = await directory(t);
  await writeFile(join(dir, 'safe.md'), source('Safe', '2026-09-14', '', '<script>alert(1)</script>\n\n[bad](javascript:alert(1))\n\n<img src=x onerror=alert(1)>'));
  const [post] = await loadPosts(dir);
  assert.doesNotMatch(post.html, /<script|<img|href="javascript:/);
  assert.match(post.html, /&lt;script&gt;/);
});
test('Markdown code fences are syntax highlighted without exposing source HTML', async t => {
  const dir = await directory(t);
  await writeFile(join(dir, 'shell.md'), source('Shell', '2026-09-14', '', '```bash\nprintf "hello"\n```'));
  const [post] = await loadPosts(dir);
  assert.match(post.html, /<pre class="hljs"><code class="hljs language-bash">/);
  assert.match(post.html, /hljs-string/);
  assert.doesNotMatch(post.html, /<script/);
});
test('HTTP serves blog, post, tools, newsroom and assets; drafts and arbitrary files stay private', async t => {
  const dir = await directory(t);
  await writeFile(join(dir, 'published.md'), source('Published'));
  await writeFile(join(dir, 'draft.md'), source('Draft', '2026-09-14', 'draft: true\n'));
  const server = createAppServer({ postsDirectory:dir, service:{ getNews:async () => ({ articles:[], sources:[] }) } });
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  t.after(() => new Promise(resolve => server.close(resolve)));
  const base = `http://127.0.0.1:${server.address().port}`;
  for (const path of ['/', '/index.html', '/blog', '/blog/', '/blog/published', '/blog/published/', '/tools', '/tools/', '/newsroom', '/newsroom/', '/assets/site.css', '/assets/site.js', '/assets/blog/entra-default-settings-header.jpg', '/assets/blog/entra-block-legacy-authentication.jpg', '/assets/blog/entra-user-default-permissions.jpg', '/assets/blog/entra-user-consent-settings.jpg', '/assets/blog/evilginx-quickstart-header.webp', '/assets/blog/entra-conditional-access-baselines-header.webp', '/assets/blog/entra-conditional-access-policy-list.webp']) {
    const response = await fetch(base + path);
    assert.equal(response.status, 200, path);
  }
  const home = await (await fetch(base)).text();
  assert.match(home, /href="\/blog\/published"/);
  assert.match(home, /id="nfs-search-index"/);
  assert.match(home, /"href":"\/blog\/published"/);
  assert.doesNotMatch(home, /\/blog\/draft/);
  const tools = await (await fetch(base + '/tools')).text();
  assert.match(tools, /id="nfs-search-index"/);
  assert.match(tools, /id="copilot-security-trail"/);
  assert.match(tools, /https:\/\/servicelogon.github.io\/copilot-security-trail\//);
  assert.match(tools, /https:\/\/servicelogon.github.io\/PasskeyLookup\//);
  for (const path of ['/blog/draft', '/blog/missing', '/blog/%2e%2e%2fserver', '/content/posts/published.md', '/blog.js', '/assets/../package.json']) {
    assert.equal((await fetch(base + path)).status, 404, path);
  }
  assert.equal(await (await fetch(base + '/blog/published', {method:'HEAD'})).text(), '');
  assert.equal((await fetch(base + '/tools', {method:'POST'})).status, 405);
  await rm(join(dir, 'published.md'));
  assert.match(await (await fetch(base)).text(), /A new chapter is on the way/);
});
function rawGet(url, headers = {}) {
  return new Promise((resolve, reject) => {
    const req = httpRequest(url, { method: 'GET', headers }, res => {
      const chunks = [];
      res.on('data', chunk => chunks.push(chunk));
      res.on('end', () => resolve({ status: res.statusCode, headers: res.headers, body: Buffer.concat(chunks) }));
    });
    req.on('error', reject);
    req.end();
  });
}
test('tag pages, sitemap, social tags, and cache headers', async t => {
  assert.match(SITE_ORIGIN, /^$|^https?:\/\/[^/]+$/);
  const dir = await directory(t);
  await writeFile(join(dir, 'published.md'), source('Published', '2026-09-14', 'tags:\n  - Identity\n  - Cloud Security\nimage: /assets/blog/entra-default-settings-header.jpg\nimageAlt: Header\n'));
  await writeFile(join(dir, 'notes.md'), source('Notes', '2026-09-01', 'tags: [Notes]\n'));
  await writeFile(join(dir, 'draft.md'), source('Draft', '2026-09-20', 'draft: true\ntags: [Secret]\n'));
  await writeFile(join(dir, 'marked.md'), source('Marked', '2026-08-01', 'tags:\n  - "<script>"\n'));
  const server = createAppServer({ postsDirectory: dir, siteOrigin: 'https://nfs.example/', service: { getNews: async () => ({ articles: [], sources: [], updatedAt: null }) } });
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  t.after(() => new Promise(resolve => server.close(resolve)));
  const base = `http://127.0.0.1:${server.address().port}`;
  const home = await (await fetch(base)).text();
  assert.match(home, /<a class="tag" href="\/blog\/tag\/identity">Identity<\/a>/);
  assert.match(home, /<a class="tag" href="\/blog\/tag\/cloud-security">Cloud Security<\/a>/);
  assert.match(home, /<a class="tag" href="\/blog\/tag\/script">&lt;script&gt;<\/a>/);
  assert.doesNotMatch(home, /<a class="tag"[^>]*>\s*<script>/);
  assert.match(home, /rel="canonical" href="https:\/\/nfs\.example\/"/);
  assert.match(home, /property="og:image" content="https:\/\/nfs\.example\/assets\/blog\/entra-default-settings-header\.jpg\?v=[a-f0-9]{12}"/);
  assert.match(home, /name="twitter:card" content="summary_large_image"/);
  assert.equal((await fetch(base)).headers.get('cache-control'), 'no-cache');
  const post = await (await fetch(base + '/blog/published')).text();
  assert.match(post, /<ul class="post-tags">.*href="\/blog\/tag\/identity"/s);
  assert.match(post, /property="og:type" content="article"/);
  assert.match(post, /property="og:image" content="https:\/\/nfs\.example\/assets\/blog\/entra-default-settings-header\.jpg\?v=[a-f0-9]{12}"/);
  assert.match(post, /rel="canonical" href="https:\/\/nfs\.example\/blog\/published"/);
  const notes = await (await fetch(base + '/blog/notes')).text();
  assert.match(notes, /name="twitter:card" content="summary"/);
  assert.doesNotMatch(notes, /property="og:image"/);
  const tag = await fetch(base + '/blog/tag/identity');
  assert.equal(tag.status, 200);
  assert.equal(tag.headers.get('cache-control'), 'no-cache');
  const tagHtml = await tag.text();
  assert.match(tagHtml, /<h1>Identity<\/h1>/);
  assert.match(tagHtml, /href="\/blog\/published"/);
  assert.doesNotMatch(tagHtml, /href="\/blog\/notes"/);
  assert.match(tagHtml, /rel="canonical" href="https:\/\/nfs\.example\/blog\/tag\/identity"/);
  const redirected = await fetch(base + '/blog/tag/Cloud%20Security', { redirect: 'manual' });
  assert.equal(redirected.status, 301);
  assert.equal(redirected.headers.get('location'), '/blog/tag/cloud-security');
  const missingTag = await fetch(base + '/blog/tag/secret');
  assert.equal(missingTag.status, 404);
  assert.equal(missingTag.headers.get('cache-control'), 'no-store');
  assert.match(await missingTag.text(), /No notes under that tag/);
  assert.equal((await fetch(base + '/blog/tag/!!!')).status, 404);
  const tools = await (await fetch(base + '/tools')).text();
  assert.match(tools, /property="og:title" content="Tools — New Frontier Security"/);
  assert.match(tools, /rel="canonical" href="https:\/\/nfs\.example\/tools"/);
  const newsroom = await (await fetch(base + '/newsroom')).text();
  assert.match(newsroom, /property="og:title" content="New Frontier Security — Newsroom"/);
  assert.match(newsroom, /rel="canonical" href="https:\/\/nfs\.example\/newsroom"/);
  assert.match(newsroom, /id="nfs-search-index"/);
  assert.match(newsroom, /"href":"\/blog\/published"/);
  assert.match(searchIndexScript([{ slug: 'x', title: '<script>', description: 'note' }]), /\\u003cscript>/);
  assert.match(newsroom, /name="twitter:card" content="summary"/);
  const sitemap = await fetch(base + '/sitemap.xml');
  assert.equal(sitemap.status, 200);
  assert.match(sitemap.headers.get('content-type'), /application\/xml/);
  assert.equal(sitemap.headers.get('cache-control'), 'no-cache');
  const xml = await sitemap.text();
  for (const loc of ['https://nfs.example/</loc>', 'https://nfs.example/newsroom', 'https://nfs.example/tools', 'https://nfs.example/blog/published', 'https://nfs.example/blog/notes', 'https://nfs.example/blog/tag/identity', 'https://nfs.example/blog/tag/cloud-security', 'https://nfs.example/blog/tag/notes']) {
    assert.match(xml, new RegExp(loc.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')));
  }
  assert.doesNotMatch(xml, /secret|draft/);
  assert.match(xml, /<lastmod>2026-09-14<\/lastmod>/);
  const robots = await fetch(base + '/robots.txt');
  assert.equal(robots.status, 200);
  assert.match(await robots.text(), /User-agent: \*\nAllow: \/\n\nSitemap: https:\/\/nfs\.example\/sitemap\.xml\n/);
  const cssHref = home.match(/\/assets\/site\.css\?v=([a-f0-9]{12})/);
  assert.ok(cssHref);
  const versioned = await fetch(base + cssHref[0]);
  assert.equal(versioned.status, 200);
  assert.equal(versioned.headers.get('cache-control'), 'public, max-age=31536000, immutable');
  const unversioned = await fetch(base + '/assets/site.css');
  assert.equal(unversioned.headers.get('cache-control'), 'public, max-age=300');
  const staleVersion = await fetch(base + '/assets/site.css?v=deadbeef0000');
  assert.equal(staleVersion.status, 200);
  assert.equal(staleVersion.headers.get('cache-control'), 'public, max-age=300');
  const gzip = await rawGet(base + '/assets/site.css?v=' + cssHref[1], { 'Accept-Encoding': 'gzip' });
  assert.equal(gzip.status, 200);
  assert.equal(gzip.headers['content-encoding'], 'gzip');
  assert.match(gzip.headers.vary, /Accept-Encoding/);
  assert.match(gzip.headers['cache-control'], /immutable/);
  assert.match(gunzipSync(gzip.body).toString('utf8'), /--pink/);
  const brotli = await rawGet(base + '/', { 'Accept-Encoding': 'br' });
  assert.equal(brotli.headers['content-encoding'], 'br');
  assert.match(brotliDecompressSync(brotli.body).toString('utf8'), /Identity/);
  const image = await rawGet(base + '/assets/newsroom-logo.png', { 'Accept-Encoding': 'gzip, br' });
  assert.equal(image.headers['content-encoding'], undefined);
  assert.match(image.headers['content-type'], /image\/png/);
  const api = await fetch(base + '/api/news');
  assert.equal(api.status, 200);
  assert.equal(api.headers.get('cache-control'), 'public, max-age=60, stale-while-revalidate=300');
  const rejected = await fetch(base + '/api/news?url=http://localhost');
  assert.equal(rejected.status, 400);
  assert.equal(rejected.headers.get('cache-control'), 'no-store');
  const failing = createAppServer({ postsDirectory: dir, service: { getNews: async () => { throw new Error('offline'); } } });
  await new Promise(resolve => failing.listen(0, '127.0.0.1', resolve));
  t.after(() => new Promise(resolve => failing.close(resolve)));
  const failed = await fetch(`http://127.0.0.1:${failing.address().port}/api/news`);
  assert.equal(failed.status, 500);
  assert.equal(failed.headers.get('cache-control'), 'no-store');
});
